name: Auto Build Docker Image

on:
  # 允许手动触发
  workflow_dispatch:
  # 定时触发（每天 UTC 21:30）
  schedule:
    - cron: '30 21 * * *'

env:
  # Docker Hub 镜像名称
  DOCKER_IMAGE: superng6/singbox
  # GitHub Container Registry (ghcr.io) 镜像名称
  GHCR_IMAGE: ghcr.io/superng6/singbox

jobs:
  # Job 1: 准备阶段 - 检查上游版本，决定是否需要构建
  prepare:
    runs-on: ubuntu-latest
    outputs:
      should_build_stable: ${{ steps.check-version.outputs.should_build_stable }}
      should_build_pre: ${{ steps.check-version.outputs.should_build_pre }}
      stable_version: ${{ steps.check-version.outputs.stable_version }}
      pre_version: ${{ steps.check-version.outputs.pre_version }}
    steps:
      - name: Checkout a repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 检查并更新版本标签文件
        id: check-version
        run: bash .github/workflows/update_release_tag.sh
        
  # Job 2-1: 构建稳定版 (Stable) - 仅在需要时运行
  build-stable:
    runs-on: ubuntu-latest
    needs: prepare
    if: needs.prepare.outputs.should_build_stable == 'true'
    permissions:
      contents: read
      packages: write # 需要写 ghcr.io 的权限
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v7
          - linux/arm64
          - linux/ppc64le
          - linux/s390x
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 准备平台名称 (用于 artifact)
        run: echo "PLATFORM_PAIR=${{ matrix.platform }}" | tr '/' '-' >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录到 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: 登录到 GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 构建并推送到双仓库 (按摘要)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          build-args: |
            VERSION=${{ needs.prepare.outputs.stable_version }}
          tags: |-
            ${{ env.DOCKER_IMAGE }}
            ${{ env.GHCR_IMAGE }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true
          cache-from: type=gha,scope=${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=${{ matrix.platform }}

      - name: 导出摘要 (digest)
        run: |
          mkdir -p /tmp/digests-stable
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests-stable/${digest#sha256:}"

      - name: 上传稳定版摘要为 artifact
        uses: actions/upload-artifact@v4
        with:
          name: digests-stable-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests-stable/*
          retention-days: 1
          
  # Job 2-2: 构建预发布版 (Pre-release) - 仅在需要时运行
  build-pre:
    runs-on: ubuntu-latest
    needs: prepare
    if: needs.prepare.outputs.should_build_pre == 'true'
    permissions:
      contents: read
      packages: write # 需要写 ghcr.io 的权限
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v7
          - linux/arm64
          - linux/ppc64le
          - linux/s390x
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 准备平台名称 (用于 artifact)
        run: echo "PLATFORM_PAIR=${{ matrix.platform }}" | tr '/' '-' >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录到 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: 登录到 GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 构建并推送到双仓库 (按摘要)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          build-args: |
            VERSION=${{ needs.prepare.outputs.pre_version }}
          tags: |-
            ${{ env.DOCKER_IMAGE }}
            ${{ env.GHCR_IMAGE }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true
          cache-from: type=gha,scope=${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=${{ matrix.platform }}

      - name: 导出摘要 (digest)
        run: |
          mkdir -p /tmp/digests-pre
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests-pre/${digest#sha256:}"

      - name: 上传预发布版摘要为 artifact
        uses: actions/upload-artifact@v4
        with:
          name: digests-pre-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests-pre/*
          retention-days: 1

  # Job 3-1: 合并稳定版镜像
  merge-stable:
    runs-on: ubuntu-latest
    needs: [prepare, build-stable]
    if: success() && needs.prepare.outputs.should_build_stable == 'true'
    permissions:
      contents: read
      packages: write
    steps:
      - name: 登录到 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: 登录到 GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 下载所有稳定版摘要
        uses: actions/download-artifact@v4
        with:
          pattern: digests-stable-*
          path: /tmp/digests
          merge-multiple: true
      
      - name: 创建并推送稳定版 manifest list 到双仓库
        working-directory: /tmp/digests
        run: |
          if [ -z "$(ls -A .)" ]; then exit 1; fi
          echo "为双仓库创建 manifest: latest, ${{ needs.prepare.outputs.stable_version }}"
          docker buildx imagetools create \
            --tag ${{ env.DOCKER_IMAGE }}:latest \
            --tag ${{ env.DOCKER_IMAGE }}:${{ needs.prepare.outputs.stable_version }} \
            --tag ${{ env.GHCR_IMAGE }}:latest \
            --tag ${{ env.GHCR_IMAGE }}:${{ needs.prepare.outputs.stable_version }} \
            $(printf '${{ env.DOCKER_IMAGE }}@sha256:%s ' *)
          
      - name: 检查双仓库的最终镜像
        if: always()
        run: |
          echo "--- 检查 Docker Hub 镜像 ---"
          docker buildx imagetools inspect ${{ env.DOCKER_IMAGE }}:latest
          echo "--- 检查 GHCR 镜像 ---"
          docker buildx imagetools inspect ${{ env.GHCR_IMAGE }}:latest

  # Job 3-2: 合并预发布版镜像
  merge-pre:
    runs-on: ubuntu-latest
    needs: [prepare, build-pre]
    if: success() && needs.prepare.outputs.should_build_pre == 'true'
    permissions:
      contents: read
      packages: write
    steps:
      - name: 登录到 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: 登录到 GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 下载所有预发布版摘要
        uses: actions/download-artifact@v4
        with:
          pattern: digests-pre-*
          path: /tmp/digests
          merge-multiple: true

      - name: 创建并推送预发布版 manifest list 到双仓库
        working-directory: /tmp/digests
        run: |
          if [ -z "$(ls -A .)" ]; then exit 1; fi
          echo "为双仓库创建 manifest: dev, ${{ needs.prepare.outputs.pre_version }}"
          docker buildx imagetools create \
            --tag ${{ env.DOCKER_IMAGE }}:dev \
            --tag ${{ env.DOCKER_IMAGE }}:${{ needs.prepare.outputs.pre_version }} \
            --tag ${{ env.GHCR_IMAGE }}:dev \
            --tag ${{ env.GHCR_IMAGE }}:${{ needs.prepare.outputs.pre_version }} \
            $(printf '${{ env.DOCKER_IMAGE }}@sha256:%s ' *)
          
      - name: 检查双仓库的最终镜像
        if: always()
        run: |
          echo "--- 检查 Docker Hub 镜像 ---"
          docker buildx imagetools inspect ${{ env.DOCKER_IMAGE }}:dev
          echo "--- 检查 GHCR 镜像 ---"
          docker buildx imagetools inspect ${{ env.GHCR_IMAGE }}:dev
