name: Build Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: '30 21 * * *'
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 更新版本
      - name: Execute Update Script
        id: up-version
        run: bash .github/workflows/update_release_tag.sh

      # 检查版本是否更新成功
      - name: Check for changes
        if: steps.up-version.outputs.status == 'success' || steps.up-version.outputs.pstatus == 'success'
        id: check-changes
        run: |
          echo "::set-output name=status::success"

      # 获得仓库中的ReleaseTag
      - name: Set Version
        if: steps.check-changes.outputs.status == 'success'
        id: set-version
        run: |
          echo "::set-output name=version::$(cat ReleaseTag | head -n1)"
          echo "::set-output name=pre_version::$(cat PreReleaseTag | head -n1)"
          echo "ReleaseTag=$(cat ReleaseTag | head -n1)"
          echo "PreReleaseTag=$(cat PreReleaseTag | head -n1)"
          echo "::set-output name=status::success"
          

      # Build and push latest_release
      - name: Build dockerfile
        if: steps.up-version.outputs.status == 'success'
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            superng6/singbox:${{ steps.set-version.outputs.version }}
            superng6/singbox:latest
          build-args: |
            VERSION=${{ steps.set-version.outputs.version }}

      # Build and push latest_prerelease
      - name: Build PreRelease dockerfile
        if: steps.up-version.outputs.pstatus == 'success'
        uses: docker/build-push-action@v4
        with:
          file: ./DockerfileDev
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            superng6/singbox:${{ steps.set-version.outputs.pre_version }}
            superng6/singbox:dev
          build-args: |
            VERSION=${{ steps.set-version.outputs.pre_version }}

      # push 最新版本号到项目中
      - name: git push
        if: steps.up-version.outputs.status == 'success' || steps.up-version.outputs.pstatus == 'success'
        id: git-push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update ReleaseTag ${{ steps.set-version.outputs.version }}"
          git push -v --progress
          echo "::set-output name=status::success"