name: Auto Build Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: '30 21 * * *'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 更新版本
      - name: Execute Update Script
        id: up-version
        run: bash .github/workflows/update_release_tag.sh

      - name: Set up QEMU
        if: steps.up-version.outputs.status == 'success' || steps.up-version.outputs.pstatus == 'success'
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        if: steps.up-version.outputs.status == 'success' || steps.up-version.outputs.pstatus == 'success'
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: steps.up-version.outputs.status == 'success' || steps.up-version.outputs.pstatus == 'success'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 获得仓库中的ReleaseTag
      - name: Set Version
        if: steps.up-version.outputs.status == 'success' || steps.up-version.outputs.pstatus == 'success'
        id: set-version
        run: |
          echo "::set-output name=version::$(cat ReleaseTag | head -n1)"
          echo "::set-output name=pre_version::$(cat PreReleaseTag | head -n1)"
          echo "ReleaseTag=$(cat ReleaseTag | head -n1)"
          echo "PreReleaseTag=$(cat PreReleaseTag | head -n1)"
          echo "::set-output name=status::success"
          
      # Build and push latest_release
      - name: Build dockerfile
        if: steps.up-version.outputs.status == 'success'
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64,linux/s390x
          push: true
          tags: |
            superng6/singbox:${{ steps.set-version.outputs.version }}
            superng6/singbox:latest
          build-args: |
            VERSION=${{ steps.set-version.outputs.version }}

      # Build and push latest_prerelease
      - name: Build PreRelease dockerfile
        if: steps.up-version.outputs.pstatus == 'success'
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64,linux/s390x
          push: true
          tags: |
            superng6/singbox:${{ steps.set-version.outputs.pre_version }}
            superng6/singbox:dev
          build-args: |
            VERSION=${{ steps.set-version.outputs.pre_version }}
