name: Manual Build Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile'
      
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      # 获得仓库中的ReleaseTag
      - name: Set Version
        id: set-version
        run: |
          echo "::set-output name=version::$(cat ReleaseTag | head -n1)"
          echo "::set-output name=pre_version::$(cat PreReleaseTag | head -n1)"
          echo "ReleaseTag=$(cat ReleaseTag | head -n1)"
          echo "PreReleaseTag=$(cat PreReleaseTag | head -n1)"
          echo "::set-output name=status::success"
          

      # Build and push latest_release
      - name: Build dockerfile
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64,linux/s390x
          push: true
          tags: |
            superng6/singbox:${{ steps.set-version.outputs.version }}
            superng6/singbox:latest
          build-args: |
            VERSION=${{ steps.set-version.outputs.version }}

      # Build and push latest_prerelease
      - name: Build PreRelease dockerfile
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64,linux/s390x
          push: true
          tags: |
            superng6/singbox:${{ steps.set-version.outputs.pre_version }}
            superng6/singbox:dev
          build-args: |
            VERSION=${{ steps.set-version.outputs.pre_version }}

